import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import TanstackProvider from "./tanstack-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* NavBar */}
        <div style={{ marginBottom: "20px" }}>
          <Link href="/">Krok 1</Link>
          <Link href="/step-2">Krok 2</Link>
          <Link href="/step-3">Krok 3</Link>
          <Link href="/contact">Kontakt</Link>
          <Link href="/about">About</Link>
        </div>

        <TanstackProvider>{children}</TanstackProvider>
      </body>
    </html>
  );
}
